In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [4]:
df=pd.read_csv("C:/Users/SREEHARI CR/data science/Social_Network_Ads.csv")

In [5]:
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [9]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [32]:
X = df.iloc[:,0:2].values
y = df.iloc[:,2].values

In [33]:
sc=StandardScaler()
x=sc.fit_transform(X)


In [35]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=0)

In [39]:
model=DecisionTreeClassifier(criterion="gini")

In [41]:
model.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [43]:
ypred=model.predict(xtest)

In [45]:
cm=confusion_matrix(ytest,ypred)

In [46]:
cm

array([[62,  6],
       [ 3, 29]], dtype=int64)

In [75]:
ac=accuracy_score(ytest,ypred)

In [76]:
ac

0.91

In [49]:
cr=classification_report(ytest,ypred)

In [50]:
cr

'              precision    recall  f1-score   support\n\n           0       0.95      0.91      0.93        68\n           1       0.83      0.91      0.87        32\n\n    accuracy                           0.91       100\n   macro avg       0.89      0.91      0.90       100\nweighted avg       0.91      0.91      0.91       100\n'

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
model2=LogisticRegression()
model2.fit(xtrain,ytrain)

LogisticRegression()

In [56]:
ypred2=model2.predict(xtest)

In [59]:
cm2=confusion_matrix(ytest,ypred2)

In [61]:
cm2

array([[65,  3],
       [ 8, 24]], dtype=int64)

In [63]:
ac2=accuracy_score(ytest,ypred2)

In [65]:
ac2

0.89

In [66]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
model3=RandomForestClassifier(n_estimators=5,criterion='entropy')

In [70]:
model3.fit(xtrain,ytrain)

RandomForestClassifier(criterion='entropy', n_estimators=5)

In [71]:
ypred3=model3.predict(xtest)

In [72]:
ypred3

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [77]:
ac3=accuracy_score(ytest,ypred3)

In [78]:
ac3

0.93

In [85]:
from sklearn.svm import SVC
model4=SVC(kernel='linear',random_state=0)

In [86]:
model4.fit(xtrain,ytrain)

SVC(kernel='linear', random_state=0)

In [88]:
ypred4=model4.predict(xtest)

In [89]:
ypred4

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [92]:
ac4=accuracy_score(ytest,ypred4)

In [93]:
ac4

0.9

In [95]:
model5=SVC(kernel='rbf',random_state=0)

In [96]:
model5.fit(xtrain,ytrain)

SVC(random_state=0)

In [97]:
ypred5=model5.predict(xtest)

In [98]:
ypred5

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [99]:
ac5=accuracy_score(ytest,ypred5)

In [100]:
ac5

0.93